### ISSUE TITLE
Keyboard shortcus do not display correctly

### ISSUE THREAD

**Issue by hannesfrank** [terence-bonhomme/rnyt#47]
Hi @terence-bonhomme, thank you for this awesome plugin!

I noticed an issue in the keyboard shortcut help:
![image](https://user-images.githubusercontent.com/4137110/150657075-9f16088f-794e-4cbd-a350-dfe80c837e42.png)

It appears that the icons used for the Arrow keys etc. are not encoded correctly in the source file and just display a unicode placeholder or something:
https://github.com/terence-bonhomme/rnyt/blob/ae4c1536955743486bf4953a8ad6df4a98b671ab/index.html#L469

**Comment by terence-bonhomme** [comment]
Hi @hannesfrank 

Thank you to report this issue, I wouldn't see this by myself.

It should be like it.

<img width="329" alt="shortcut" src="https://user-images.githubusercontent.com/95495533/150658116-f05da865-de9b-4bbc-a8d2-595f77a5efc5.png">

I will try to replace these arrows with html codes like  `&#10132;`

**Comment by terence-bonhomme** [comment]
I've deployed the fix. Can you tell me if it is okay?

**Comment by terence-bonhomme** [comment]
I could reproduce this issue on Linux with Chrome. Many Unicode characters are not displayed. It shows empty squares. I replaced the characters with text.
