### ISSUE TITLE
url duration is not reflected in the link

### ISSUE THREAD

**Issue by Eikosa** [terence-bonhomme/rnyt#49]
For example, if I change the time from 3:38 to 3:35, the link still redirects to 3:38

**Comment by terence-bonhomme** [comment]
Did you change the time like this screenshot?

<img width="98" alt="time" src="https://user-images.githubusercontent.com/95495533/151005772-6fb866cf-2646-45d2-833c-afec154066a1.png">

1. RemNote : left click on the link
2. Youtube : copy the url on YouTube, example : https://www.youtube.com/watch?v=rRfwyzikM6M&t=218
3. RemNote : right click on the link
4. Paste the link into the input
5. Calculate the time in seconds, example 3:35 = 215
5. Edit the t= part, example : https://www.youtube.com/watch?v=rRfwyzikM6M&t=215
6. Valid with enter or the button Link to Website

The link is not 3:38, it is only a name. In fact, the link is like [name](link), RemNote uses the markdown language, for example `[3:38](https://www.youtube.com/watch?v=rRfwyzikM6M&t=218)`.

You could make a new timestamp with the plugin and move the child notes into this.

**Comment by terence-bonhomme** [comment]
The plugin uses the timestamp from the url, but it could be the name too.

If the project is edited. The user could lie, it could work with the plugin, but the link will be incorrect.

`[0:50](https://www.youtube.com/watch?v=rRfwyzikM6M&t=100)`
Plugin : 0:50
Link : 1:40

**Comment by Eikosa** [comment]
> The plugin uses the timestamp from the url, but it could be the name too.
> 
> If the project is edited. The user could lie, it could work with the plugin, but the link will be incorrect.
> 
> `[0:50](https://www.youtube.com/watch?v=rRfwyzikM6M&t=100)` Plugin : 0:50 Link : 1:40

Yep i mean that

**Comment by terence-bonhomme** [comment]
In fact, it is already possible to lie to the plugin.

The plugin design has to respect the "read and create" permissions. It is a choice to limit the risks. The plugin needs the "modify" permission to add a function that corrects the link. It could be more powerful with more permissions. It is not possible as it is.

**Comment by terence-bonhomme** [comment]
You can use this plugin to update a link.

https://update-rem-timestamp.glitch.me
height: 100
width: 150
permissions: read, create, modify
location: popup

I could use this code later.

**Comment by Eikosa** [comment]
update link is not working now
